/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tp1dpbo2022;

import entitas.ent_Buku;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import query.sql_query_buku;

/**
 *
 * @author LENOVO
 */
public class formDataBuku extends javax.swing.JDialog {
    BufferedImage image;
    String path;
    byte[] bitArray = null;
    
    /**
     * Creates new form formDataBuku2
     */
    public formDataBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_Buku = new javax.swing.JPanel();
        label_JudulFormBuku = new javax.swing.JLabel();
        lbl_penerbit = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        lbl_inpGambar1 = new javax.swing.JLabel();
        txtField_desc = new javax.swing.JTextField();
        txtField_author = new javax.swing.JTextField();
        txtField_penerbit = new javax.swing.JTextField();
        jScrollPane_imgInpBuku = new javax.swing.JScrollPane();
        imgInpBuku = new javax.swing.JLabel();
        txtField_dirGambarBuku = new javax.swing.JTextField();
        btn_choseImgBuku = new javax.swing.JButton();
        btn_ClearFormBuku = new javax.swing.JButton();
        btn_InsertFormBuku = new javax.swing.JButton();
        btn_cancelInpBuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_JudulFormBuku.setFont(new java.awt.Font("Myriad Pro", 2, 24)); // NOI18N
        label_JudulFormBuku.setText("Form Insert Data Buku");

        lbl_penerbit.setText("Penerbit");

        lbl_author.setText("Author");

        lbl_desc.setText("Desc");

        lbl_inpGambar1.setText("Gambar");

        txtField_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_descActionPerformed(evt);
            }
        });

        txtField_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_authorActionPerformed(evt);
            }
        });

        txtField_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_penerbitActionPerformed(evt);
            }
        });

        jScrollPane_imgInpBuku.setViewportView(imgInpBuku);

        txtField_dirGambarBuku.setEditable(false);

        btn_choseImgBuku.setText("Choose");
        btn_choseImgBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choseImgBukuActionPerformed(evt);
            }
        });

        btn_ClearFormBuku.setText("Clear");
        btn_ClearFormBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearFormBukuActionPerformed(evt);
            }
        });

        btn_InsertFormBuku.setText("Insert");
        btn_InsertFormBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertFormBukuActionPerformed(evt);
            }
        });

        btn_cancelInpBuku.setText("<< Back");
        btn_cancelInpBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelInpBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_BukuLayout = new javax.swing.GroupLayout(form_Buku);
        form_Buku.setLayout(form_BukuLayout);
        form_BukuLayout.setHorizontalGroup(
            form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_BukuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(form_BukuLayout.createSequentialGroup()
                            .addComponent(lbl_author)
                            .addGap(18, 18, 18)
                            .addComponent(txtField_author, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(form_BukuLayout.createSequentialGroup()
                            .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_inpGambar1)
                                .addComponent(lbl_desc))
                            .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(form_BukuLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(form_BukuLayout.createSequentialGroup()
                                            .addComponent(txtField_dirGambarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_choseImgBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane_imgInpBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(form_BukuLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(txtField_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(form_BukuLayout.createSequentialGroup()
                            .addComponent(lbl_penerbit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtField_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(form_BukuLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btn_InsertFormBuku)
                            .addGap(18, 18, 18)
                            .addComponent(btn_ClearFormBuku)
                            .addGap(18, 18, 18)
                            .addComponent(btn_cancelInpBuku)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_BukuLayout.createSequentialGroup()
                        .addComponent(label_JudulFormBuku)
                        .addGap(16, 16, 16)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        form_BukuLayout.setVerticalGroup(
            form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_BukuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(label_JudulFormBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_penerbit)
                    .addComponent(txtField_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_author)
                    .addComponent(txtField_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_desc)
                    .addComponent(txtField_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_inpGambar1)
                        .addComponent(txtField_dirGambarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_choseImgBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_imgInpBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(form_BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InsertFormBuku)
                    .addComponent(btn_ClearFormBuku)
                    .addComponent(btn_cancelInpBuku))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(form_Buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(form_Buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_descActionPerformed

    private void txtField_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_authorActionPerformed

    private void txtField_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_penerbitActionPerformed

    private void btn_choseImgBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choseImgBukuActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser(System.getProperty("user.home"));
        choose.setFileSelectionMode(JFileChooser.FILES_ONLY);
        choose.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp|","jpg","png","bmp"));
        if(choose.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            java.io.File file = choose.getSelectedFile();
            try {
                if (file.length() > 1024000) {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(rootPane, "Gambar Terlalu Besar", "Max 1MB", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    image  = ImageIO.read(file);
                    Image inpImg = image.getScaledInstance(imgInpBuku.getWidth(), imgInpBuku.getHeight(), image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(inpImg);
                    imgInpBuku.setIcon(icon);
                    path = file.getAbsolutePath();
                    txtField_dirGambarBuku.setText(file.getName());
                }
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btn_choseImgBukuActionPerformed

    private void btn_ClearFormBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearFormBukuActionPerformed
        // TODO add your handling code here:
        txtField_penerbit.setText("");
        txtField_author.setText("");
        txtField_desc.setText("");
        txtField_dirGambarBuku.setText("");
        imgInpBuku.setIcon(null);
    }//GEN-LAST:event_btn_ClearFormBukuActionPerformed

    private void btn_InsertFormBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertFormBukuActionPerformed
        // TODO add your handling code here:
        if ((txtField_author.getText().equals("")) || (txtField_dirGambarBuku.getText().equals("")) || (txtField_penerbit.getText().equals("")) || (txtField_desc.getText().equals(""))){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Field tidak boleh ada yang kosong!");
        }else{
            try {
                ent_Buku databuku = new ent_Buku();

                databuku.setPenerbit(txtField_penerbit.getText());
                databuku.setAutor(txtField_author.getText());
                databuku.setDesc(txtField_desc.getText());
                
                //input gambar
                ByteArrayOutputStream outImg = new ByteArrayOutputStream();
                File imgBuku = new File(path);
                FileInputStream input = new FileInputStream(imgBuku);
                
                try {
                    byte[] buffer = new byte[1024];
                    for(int readbyte;(readbyte = input.read(buffer)) !=-1;){
                        outImg.write(buffer, 0, readbyte);
                    }
                    
                    bitArray = outImg.toByteArray();
                    databuku.setImg(bitArray);
                } catch (Exception e) {
                }

                sql_query_buku query = new sql_query_buku();
                query.insert(databuku);
                
                txtField_dirGambarBuku.setText("");
                imgInpBuku.setIcon(null);
                txtField_penerbit.setText("");
                txtField_author.setText("");
                txtField_desc.setText("");   
                
                dispose();
                MainMenu menu = new MainMenu();
                menu.setVisible(true);
            } catch (Exception e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Proses Insert Error!");
            }   
        }
    }//GEN-LAST:event_btn_InsertFormBukuActionPerformed

    private void btn_cancelInpBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelInpBukuActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_cancelInpBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDataBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ClearFormBuku;
    private javax.swing.JButton btn_InsertFormBuku;
    private javax.swing.JButton btn_cancelInpBuku;
    private javax.swing.JButton btn_choseImgBuku;
    private javax.swing.JPanel form_Buku;
    private javax.swing.JLabel imgInpBuku;
    private javax.swing.JScrollPane jScrollPane_imgInpBuku;
    private javax.swing.JLabel label_JudulFormBuku;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JLabel lbl_inpGambar1;
    private javax.swing.JLabel lbl_penerbit;
    private javax.swing.JTextField txtField_author;
    private javax.swing.JTextField txtField_desc;
    private javax.swing.JTextField txtField_dirGambarBuku;
    private javax.swing.JTextField txtField_penerbit;
    // End of variables declaration//GEN-END:variables
}
